apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gw-classification-pipeline
spec:
  workspaces:
    - name: dpk-pipeline-ws
  params:
    - name: S3_BUCKET_PATH
      description: Bucket name or bucket name and path for the root S3 folder (e.g.. bucket-wikimedia-1 or bucket-wikimedia-1/run1, etc) 
      type: string
    - name: GW_MATH_OUTPUT
      type: string
      description: The output folder for the GW Math Classifier
    - name: GW_MATH_INPUT
      type: string
      description: The input folder for the GW Math Classifier
  tasks:
    - name: execute-gw-classification-task
      taskRef:
        name: gw-classification-task
      workspaces:
        - name: rayjobs
          workspace: dpk-pipeline-ws
      params:
        - name: S3_BUCKET_PATH
          value: "$(params.S3_BUCKET_PATH)" 
        - name: GW_MATH_OUTPUT
          value: "$(params.GW_MATH_OUTPUT)"  
        - name: GW_MATH_INPUT
          value: "$(params.GW_MATH_INPUT)"
