apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ededup-gwclassifiation
spec:
  pipelineRef:
    name: ededup-gwclassification
  params:
      - name: S3_BUCKET_PATH
        value: "bucket-wikimedia-1"   
      - name: EDEDUP_INPUT
        value: "take6_md"
      - name: EDEDUP_OUTPUT
        value: "mt-ededup-2"
      - name: GW_MATH_INPUT
        value: "mt-ededup-2"
      - name: GW_MATH_OUTPUT
        value: "gw_classification_mt-2"
  workspaces:
      - name: dpk-pipeline-ws
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi