apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: docling
spec:
  params:
    - name: S3_BUCKET_PATH
      type: string
    - name: HTML_ZIP
      type: string
    - name: DOCLING_OUTPUT
      type: string
  workspaces:
    - name: rayjobs
      description: A workspace to mount the job YAML.
  steps:
    - name: run-docling-job
      image: bitnami/kubectl:latest
      env:
        - name: S3_BUCKET_PATH
          value: $(params.S3_BUCKET_PATH)
        - name: HTML_ZIP
          value: $(params.HTML_ZIP)
        - name: DOCLING_OUTPUT
          value: $(params.DOCLING_OUTPUT)

      script: |
        #!/bin/sh
        envsubst < /workspace/rayjobs/data-prep-kit/transforms/language/docling2parquet/docling2parquet-rayjob.yaml > /workspace/rayjobs/docling-task.yaml
        cat /workspace/rayjobs/docling-task.yaml
        kubectl apply -f /workspace/rayjobs/docling-task.yaml
        echo "Waiting for Kubernetes job/rayjob-docling to finish or timeout after 24h..."
        kubectl wait --for=jsonpath='{.status.jobDeploymentStatus}'=Complete rayjob/rayjob-docling --timeout=24h
        echo "Kubernetes job/rayjob-ededup completed. Check log for completion status..."

