apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: text-encoder
spec:
  params:
    - name: TEXT_ENCODER_LANCEDB_DATA_URI
      type: string
    - name: TEXT_ENCODER_FRAGMENT_JSON_FOLDER
      type: string
    - name: TEXT_ENCODER_DATASET_NAME
      type: string
    - name: TEXT_ENCODER_MODEL_NAME
      type: string
      default: "ibm-granite/granite-embedding-30m-english"
    - name: TEXT_ENCODER_INPUT_FOLDER
      type: string
    - name: TEXT_ENCODER_OUTPUT_FOLDER
      type: string
    - name: TEXT_ENCODER_CONTENTS_NAME
      type: string
      default: "contents"
    - name: TEXT_ENCODER_DOCUMENT_ID_NAME
      type: string
      default: "document_id"
    - name: RUNTIME_NUM_WORKERS
      type: string
      default: "10"
  workspaces:
    - name: rayjobs
      description: A workspace to mount the job YAML.
  steps:
    - name: run-text-encoder-job
      image: quay.io/dataprep1/data-prep-kit/kubectl:latest
      env:
        - name: TEXT_ENCODER_LANCEDB_DATA_URI
          value: $(params.TEXT_ENCODER_LANCEDB_DATA_URI)
        - name: TEXT_ENCODER_FRAGMENT_JSON_FOLDER
          value: $(params.TEXT_ENCODER_FRAGMENT_JSON_FOLDER)
        - name: TEXT_ENCODER_DATASET_NAME
          value: $(params.TEXT_ENCODER_DATASET_NAME)
        - name: TEXT_ENCODER_MODEL_NAME
          value: $(params.TEXT_ENCODER_MODEL_NAME)
        - name: TEXT_ENCODER_INPUT_FOLDER
          value: $(params.TEXT_ENCODER_INPUT_FOLDER)
        - name: TEXT_ENCODER_OUTPUT_FOLDER
          value: $(params.TEXT_ENCODER_OUTPUT_FOLDER)
        - name: TEXT_ENCODER_CONTENTS_NAME
          value: $(params.TEXT_ENCODER_CONTENTS_NAME)
        - name: TEXT_ENCODER_DOCUMENT_ID_NAME
          value: $(params.TEXT_ENCODER_DOCUMENT_ID_NAME)
        - name: RUNTIME_NUM_WORKERS
          value: $(params.RUNTIME_NUM_WORKERS)
      script: |
        #!/bin/sh
        envsubst < /workspace/rayjobs/data-prep-kit/transforms/language/text_encoder/text-encoder-rayjob.yaml > /workspace/rayjobs/text-encoder-task.yaml
        cat /workspace/rayjobs/text-encoder-task.yaml
        kubectl apply -f /workspace/rayjobs/text-encoder-task.yaml
        echo "Watiing for Kubernetes job/text-encoder-task to finish or timeout after 24h..."
        kubectl wait --for=jsonpath='{.status.jobDeploymentStatus}'=Complete rayjob/rayjob-text-encoder --timeout=24h
        echo "Kubernetes job/rayjob-text-encoder completed. Check log for completion status..."

