# fluent-bit.conf
# Usage:
# kubectl create configmap fluentbit-config-for-ray --from-file=fluent-bit.conf -n NAMESPACE
#[SERVICE]
#    Flush        1
#    Log_Level    info
#    Daemon       off
#    Parsers_File parsers.conf # You might include other parser files
#kubectl delete configmap fluentbit-config-for-ray
# kubectl create configmap fluentbit-config-for-ray --from-file=../../../scripts/k8s-setup/fluent-bit.conf
[INPUT]
    Name          tail
    Path          /tmp/ray/session_latest/logs/*.log
    Tag           ray.*
    Path_key      true
    Refresh_Interval 5
#    DB            /var/log/flb_ray_logs.db # Optional: Persistence for tailing progress
#    Mem_Buf_Limit 5MB
#    Skip_Long_Lines On
#    Parser        docker  # Adjust if your Ray logs aren't in Docker format

[FILTER]
    Name          modify
    Match         ray.*
    Add POD_LABEL ${POD_LABELS}

[OUTPUT]
    Name          s3
    Match         ray.*
    bucket        ${S3_BUCKET_NAME}
    region        ${S3_REGION}
    Endpoint      ${AWS_ENDPOINT_URL}
    compression   gzip
    s3_key_format /ray-logs/%Y-%m-%d/$TAG.gz
    # S3 object key format
    # The S3 plugin buffers data to the filesystem before uploading. The store_dir parameter is not typically used