# (C) Copyright IBM Corp. 2024.
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

import os
import sys
from pathlib import Path
import timeit
import asyncio
from prefect import task, flow
from data_processing.utils import get_logger
from data_processing.data_access import DataAccess, DataAccessLocal, DataAccessS3
from data_processing.data_access.data_access_memory import DataAccessMemory
from data_processing.transform.transform_factory import create_transform_from_file

prefect_path = Path(__file__).resolve().parents[2] / "prefect_workflow/utils"
sys.path.append(str(prefect_path))

from workflow_validator import load_workflow_config, validate_workflow_config


@task(name="execute_step", task_run_name="{name}")
def __execute_step(self, name, op_def, data_access, batch_files):
    start = timeit.default_timer()

    for f in batch_files:
        table, _ = data_access.get_table(f)
        num_rows = table.num_rows
        # see if necessary to flag
        if num_rows == 0:
            continue
        self.logger.info('\n\n>>> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        self.logger.info('Step ID: %s', op_def['name'])
        self.logger.info('>>> Starting execution: Step Name: %s, operator: %s',
                         op_def['name'], op_def['transform'])

        transform = create_transform_from_file(op_def['transform'], op_def['params'])
        table_list, metadata = transform.transform(table)
        if len(table_list) > 0:
            data_access.save_table(f, table_list[0])


        self.logger.info('\n> Number of rows: %s, \n> metadata: %s', num_rows, metadata)
        self.logger.info('>>> ================================================================')

    time_taken = timeit.default_timer() - start

    node_stats = {
        'name': name,
        'time_taken': time_taken,
        'node_status': "Completed"
    }
    self.logger.info(node_stats)

    return data_access


def get_in_memory(batch_files: list, data_access: DataAccess ) -> DataAccessMemory:
    in_memory = DataAccessMemory()
    for f in batch_files:
        in_memory.save_table(f, data_access.get_table(f)[0])

    return in_memory


def save_in_memory_to_file(batch_files: list, in_memory: DataAccessMemory, data_access: DataAccess):
    for f in batch_files:
        filename = os.path.join(data_access.get_output_folder(), os.path.basename(f))
        data_access.save_table(str(filename), in_memory.get_table(f)[0])

class AbstractOrchestrator:
    def __init__(self) -> None:
        self.logger = get_logger(__name__)

    def _get_data_access(self, global_config: dict) -> DataAccess:
        data_access = global_config['data_access']
        if global_config['data_storage_type'] == 's3':
            return DataAccessS3(**data_access)
        else:
        # anything else is local data
            return DataAccessLocal(**data_access)

    def _create_node_id_to_index_map(self, flow_def: dict) -> dict:
        """
        Return a mapping between each node ID and its corresponding index, representing the position where it
        appears in the original JSON node sequence.
        """
        node_id_to_index_map = {}
        index = 0
        for node in flow_def:
            node_id_to_index_map[node["name"]] = index
            index = index + 1
        return node_id_to_index_map

    async def orchestrate(self, flow_def: dict):
        futures = []
        results = []
        """
        Executes the given flow and returns the DataAccess generated by the flow
        """
        if 'flow' in flow_def:
            flow_def = flow_def.get('flow')

        global_config = flow_def.get("global_config", {}) | {"flow_definition": flow_def}
        # find way to determine data access factory based on flow_definition
        da = self._get_data_access(flow_def.get("global_config"))
        op_dag = flow_def.get("sequence", [])

        # get batch of files from data access
        # keep track of the files to use and process them after acquiring via in-memory

        try:
            while True:
                batch_files = da.get_batches_to_process()
                if len(batch_files) == 0:
                    break

                # generate prefect code
                prefect_code = "@flow(timeout_seconds=3600,retries=3, retry_delay_seconds=60, log_prints=True)"
                prefect_code += "\nasync def dpk_pipeline(orch_obj, name, op_dag, in_memory, data_access, batch_files):"

                # execute the ingest step
                ingest_operator = op_dag[0]
                name = ingest_operator["name"]
                node_id_to_index_map = self._create_node_id_to_index_map(op_dag)
                index = node_id_to_index_map[ingest_operator["name"]]

                # get in-memory tables from the paths
                in_memory_da = get_in_memory(batch_files, da)
                prefect_code += f"\n\tdata_access_{index + 1} = __execute_step.submit(orch_obj, \"{name}\", op_dag[0], in_memory, batch_files)"

                i = 1
                # execute the rest of the pipeline
                for op_def in op_dag[1:]:
                    if op_def["input_edges"]:
                        # TODO expecting only one input edge for now
                        first_edge = op_def["input_edges"][0]
                        prev_index = node_id_to_index_map[first_edge["node_name_ref"]]
                        index = node_id_to_index_map[op_def["name"]]
                        name = op_def["name"]
                        if op_def["output_edges"]:
                            prefect_code += f"\n\tdata_access_{index + 1} = __execute_step.submit(orch_obj, \"{name}_{i}\", op_dag[{i}], data_access_{prev_index + 1}.result(), batch_files)"
                        else:
                            prefect_code += f"\n\tdata_access_{index + 1} = __execute_step.submit(orch_obj, \"{name}_{i}\", op_dag[{i}],  data_access_{prev_index + 1}.result(), batch_files)"
                        i = i + 1

                prefect_code += f"\n\tsave_in_memory_to_file(batch_files, data_access_{index + 1}.result(), data_access)"

                self.logger.info("Generated Code:\n")
                self.logger.info(prefect_code)

                local_env = {}
                exec(prefect_code, globals(), local_env)
                dpk_pipeline = local_env['dpk_pipeline']

                # execute the flow
                #future = executor.submit(dpk_pipeline, self, name, op_dag, in_memory_da, da, batch_files)
                future = dpk_pipeline(self, name, op_dag, in_memory_da, da, batch_files)
                futures.append(future)

            #wait(futures)
            results = await asyncio.gather(*futures, return_exceptions=True)
            return da

        except Exception as e:
            self.logger.error(f"Caught exception: {e}")

        finally:
            for i, res in enumerate(results):
                if isinstance(res, Exception):
                    self.logger.error(f"Batch {i}failed: {res}")
                else:
                    self.logger.info(f"Batch {i}: succeed")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename = sys.argv[1]
        flow_def = load_workflow_config(filename)
        validate_workflow_config(flow_def)

        ao = AbstractOrchestrator()
        asyncio.run(ao.orchestrate(flow_def))
    else:
        print("Please provide a filename as a command-line argument.")
