import json
import logging
import os
import sys
from pathlib import Path
import timeit
import pyarrow as pa
from prefect import task, flow
#from data_processing.data_access import DataAccess, DataAccessLocal, DataAccessS3
from data_processing.utils import get_logger
#import data_processing's transforms to get factory

factory_path = Path(__file__).resolve().parents[2] / "data-processing-lib/python/src/data_processing/transform"
da_path = Path(__file__).resolve().parents[2] / "data-processing-lib/python/src/data_processing/data_access"
sys.path.append(str(factory_path))
sys.path.append(str(da_path))
from transform_factory import create_transform_from_file
from data_access_s3 import DataAccessS3
from data_access_local import DataAccessLocal
from data_access_memory import DataAccessMemory
from data_access import DataAccess


@task(name="execute_step", task_run_name="{name}")
def __execute_step(self, name, op_def, global_config, data_access, batch_files):
    start = timeit.default_timer()

    # the step will be skipped if this is not ingest operator and results from previous step is empty
    for f in batch_files:
        table, _ = data_access.get_table(f)
        num_rows = table.num_rows
        # see if necessary to flag
        if num_rows == 0:
            continue
        self.logger.info('\n\n>>> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        self.logger.info('Step ID: %s', op_def['name'])
        self.logger.info('>>> Starting execution: Step Name: %s, operator: %s',
                         op_def['name'], op_def['transform'])

        transform = create_transform_from_file(op_def['transform'], op_def['params'])
        table_list, metadata = transform.transform(table)
        if len(table_list) > 0:
            data_access.save_table(f, table_list[0])


        self.logger.info('\n> Number of rows: %s, \n> metadata: %s', num_rows, metadata)
        self.logger.info('>>> ================================================================')

    time_taken = timeit.default_timer() - start

    node_stats = {
        'name': op_def['name'],
        'time_taken': time_taken,
        'node_status': "Completed"
    }
    self.logger.info(node_stats)

    return data_access


class AbstractOrchestrator:
    def __init__(self) -> None:
        self.logger = get_logger(__name__)

    def _get_data_access(self, global_config: dict) -> DataAccess:
        data_access = global_config['data_access']
        if global_config['data_storage_type'] == 's3':
            return DataAccessS3(**data_access)
        else:
        # anything else is local data
            return DataAccessLocal(**data_access)

    def _create_node_id_to_index_map(self, flow_def: dict) -> dict:
        """
        Return a mapping between each node ID and its corresponding index, representing the position where it
        appears in the original JSON node sequence.
        """
        node_id_to_index_map = {}
        index = 0
        for node in flow_def:
            node_id_to_index_map[node["name"]] = index
            index = index + 1
        return node_id_to_index_map

    def _get_in_memory(self, batch_files: list, data_access: DataAccess ) -> DataAccessMemory:
        in_memory = DataAccessMemory()
        for f in batch_files:
            in_memory.save_table(f, data_access.get_table(f)[0])

        return in_memory

    def _save_in_memory_to_file(self, batch_files: list, in_memory: DataAccessMemory, data_access: DataAccess):
        for f in batch_files:
            filename = os.path.join(data_access.get_output_folder(), os.path.basename(f))
            print(filename)
            data_access.save_table(str(filename), in_memory.get_table(f)[0])


    def orchestrate(self, flow_def: dict):
        """
        Executes the given flow and returns the DataAccess generated by the flow
        """
        global_config = flow_def.get("global_config", {}) | {"flow_definition": flow_def}
        # find way to determine data access factory based on flow_definition
        da = self._get_data_access(flow_def.get("global_config"))
        op_dag = flow_def.get("sequence", [])

        # get batch of files from data access
        # keep track of the files to use and process them after acquiring via in-memory
        batch_files = da.get_batches_to_process()
        while len(batch_files) > 0:
            # get in-memory tables from the paths
            prefect_code = "@flow(timeout_seconds=3600,retries=3, retry_delay_seconds=60, log_prints=True)"
            prefect_code += "\ndef dpk_pipeline(orch_obj, name, op_dag, global_config, data_access, batch_files):"

            # execute the ingest step
            ingest_operator = op_dag[0]
            name = ingest_operator["name"]
            node_id_to_index_map = self._create_node_id_to_index_map(op_dag)
            index = node_id_to_index_map[ingest_operator["name"]]

            in_memory_da = self._get_in_memory(batch_files, da)
            prefect_code += f"\n\tdata_access_{index + 1} = __execute_step.submit(orch_obj, \"{name}\", op_dag[0], global_config, data_access, batch_files)"

            i = 1
            # execute the rest of the pipeline
            for op_def in op_dag[1:]:
                if op_def["input_edges"]:
                    # TODO expecting only one input edge for now
                    first_edge = op_def["input_edges"][0]
                    prev_index = node_id_to_index_map[first_edge["node_name_ref"]]
                    index = node_id_to_index_map[op_def["name"]]
                    name = op_def["name"]
                    print(op_dag[1])
                    print(type(op_dag))
                    if op_def["output_edges"]:
                        prefect_code += f"\n\tdata_access_{index + 1} = __execute_step.submit(orch_obj, \"{name}_{i}\", op_dag[{i}], global_config, data_access_{prev_index + 1}.result(), batch_files)"
                    else:
                        prefect_code += f"\n\tdata_access_{index + 1} = __execute_step.submit(orch_obj, \"{name}_{i}\", op_dag[{i}], global_config, data_access_{prev_index + 1}.result(), batch_files)"
                    i = i + 1

            # return data_access from executed run
            prefect_code += f"\n\treturn data_access_{index + 1}"

            print("Generated Code:\n")
            print(prefect_code)

            local_env = {}
            exec(prefect_code, globals(), local_env)
            dpk_pipeline = local_env['dpk_pipeline']
            # execute the flow
            final_da = dpk_pipeline(self, name, op_dag, global_config, in_memory_da, batch_files).result()
            self._save_in_memory_to_file(batch_files, final_da, da)

            batch_files = da.get_batches_to_process()

        return da


if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename = sys.argv[1]
        ao = AbstractOrchestrator()
        try:
            with open(filename, 'r') as json_file:
                flow_def = json.load(json_file).get('flow')
                ao.orchestrate(flow_def)
        except FileNotFoundError:
            print(f"Error: File '{filename}' not found.")
        except Exception as e:
            print(f"An error occurred: {e}")
    else:
        print("Please provide a filename as a command-line argument.")
